name: tests

on:
  push:
    branches:
      - main # 监听 main 分支的 push 操作

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出仓库代码
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Step 2: 设置 JDK 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17 

      # Step 3: 缓存 Maven 包
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Step 4: 使用 Maven 执行测试
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
